name: 'Tag kubectl-build-deploy-dind image as production'

on:
  release:
    types: [published]

jobs:
  pull-tag-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Set tag version for tag
      if: "startsWith(github.ref, 'refs/tags/')"
      id: version_tag
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "tag is $VERSION"
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          # docker.io/${{ github.repository_owner }}/kubectl-build-deploy-dind
          ghcr.io/${{ github.repository_owner }}/kubectl-build-deploy-dind
        tags: |
          type=raw,value=production
    # - name: Login to DockerHub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Image to multiple registries
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: docker.io/uselagoon/kubectl-build-deploy-dind:${{ env.VERSION }}
        dst: |
          ${{ steps.meta.outputs.tags }}
